---
- name: Prepare Ubuntu
  hosts: localhost
  vars:
    my_packages:
      - git
      - htop
      - python-psutil
  pre_tasks:
    - name: Update Repositories
      apt:
        update_cache: yes
        changed_when: false
  tasks:
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
...
