---
- name: Prepare Ubuntu
  hosts: localhost
  become: yes
  vars:
    my_packages:
      - git
      - htop
      - python-psutil
      - vim
      - tree
      - openssh-server
      - adapta-gtk-theme
      - gnome-tweaks
  pre_tasks:
    - name: Update Repositories
      apt:
        update_cache: yes
      changed_when: false
  tasks:
    - include: tasks/repositories.yml
    - include: tasks/rpm_keys.yml
    - include: tasks/packages.yml
    - include: tasks/gnome.yml
    - include: tasks/firewall.yml
...
