---
- name: Local Playbook
  hosts: localhost
  become: true
  tasks:
    - name: Install the lates version of {{ item }} package
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - htop


...
