---
- name: Prepare Ubuntu
  hosts: localhost
  become: yes
  vars:
    my_packages:
      - git
      - htop
      - python-psutil
      - vim
      - tree
      - openssh-server
      - gnome-tweaks
      - snapd
      - snapd-xdg-open
      - gnome-sushi
  pre_tasks:
    - name: Update Repositories
      apt:
        update_cache: yes
      changed_when: false
  tasks:
    - include: tasks/rpm_keys.yml
    - include: tasks/packages.yml
    - include: tasks/snaps.yml
    - include: tasks/gnome.yml
    - include: tasks/firewall.yml
    - include: tasks/motd.yml
    - include: tasks/cleanup.yml
...
