---
- name: Local Playbook
  hosts: localhost
  become: true
  vars:
    my_packages:
      - git
      - htop
  tasks:
    - name: Install the latest version of packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        "{{ my_packages }}"

...
