---
- name: Copy wallpaper file
  copy:
    src: files/cloudWallpaperDark.jpg
    dest: /home/daniel/.wallpaper.jpg
    owner: daniel
    group: daniel
    mode: 600
- name: Set GNOME wallpaper
  become_user: daniel
  dconf: 
    key: "/org/gnome/desktop/background/picture-uri" 
    value: "'file:///home/daniel/.wallpaper.jpg'"

...
