---
- name: Install the latest version of packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    "{{ my_packages }}"
- name: Install Deb Zoom package from URL
  apt:
    deb: https://zoom.us/client/5.4.53391.1108/zoom_i386.deb

...
