---
- vars:
    my_packages:
      - git
      - htop
      - python-psutil
  tasks:
    - name: Install the latest version of packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        "{{ my_packages }}"

...
